### ISSUE TITLE
Jaeger UI does not capture errorneus tests properly

### ISSUE THREAD

**Issue by oleg-nenashev** [craigatk/opentelemetry-gradle-plugin#126]
In the Jaeger UI, the failing tests are not marked a failure, because the `error` tag is not boolean true/false, but includes the message instead

<img width="1497" alt="Screenshot 2024-04-02 at 16 32 57" src="https://github.com/craigatk/opentelemetry-gradle-plugin/assets/3000480/25b5607c-2db4-4ed5-bcf7-da03f95fdb47">

**Comment by craigatk** [comment]
Thanks for raising this issue! I'll work on a fix - likely moving the error message to a different attribute and make `error` into a boolean.

**Comment by craigatk** [comment]
I switched error to be a boolean and put the message string in error_message and released a new plugin version `1.10.0` with the changes. Thanks again for reporting this issue!
