### ISSUE TITLE
Option to create hierarchical spans for tests

### ISSUE THREAD

**Issue by felixscheinost** [craigatk/opentelemetry-gradle-plugin#146]
We implemented a change to how traces are generated for ourselves and wanted to check whether you would be interested in getting a PR for upstreaming the change.

Currently the tests are recored in the trace as a "flat" list of spans, one per test feature, right?

So:

- `:test`
   - `FooTest foo should return bar()`
   - `FooTest foo should return baz()`
   - ...

We wanted to "group" those spans based on Gradle Test executor and test class. This is handy when using Gradle to execute tests in parallel, as it is easy to see which test classes where scheduled on the same executor by Gradle.

The trace would then look like that (the names could be changed obviously)

- `:test`
  -  `Gradle Test Executor 1`
     - `FooTest`
       - `FooTest foo should return bar()`
     
Would you be interested in such a change? In my opinion that is a good default but it could be configurable opt-in as well.

The change only required a few changes to `OpenTelemetryTestListener`.

For testing we also implemented a integration test which starts Jaeger in a Testcontainer, then fetches the trace from Jaeger using the API. The test asserts that the correct spans are generated and in the correct hierarchy.

**Comment by craigatk** [comment]
@felixscheinost thanks for offering to add this capability into the plugin! I think it sounds like a great addition. And agreed that having it the default sounds good, plus having a configuration option if users want to keep the current behavior.

Also that integration test that uses Testcontainers with Jaegar sounds awesome, better than my current approach of using Wiremock and doing weak string searching in the POST body. If you're also up for including that type of test for this behavior, then I can work to incorporate that technique in other tests in the repo as well.

Thanks again! :)

**Comment by craigatk** [comment]
Created a new release `1.13.0` with this feature - thanks again for your contribution! 🎉 

<img width="861" alt="per-test-spans" src="https://github.com/craigatk/opentelemetry-gradle-plugin/assets/252174/73dd0d4b-8008-4ea0-bb1a-7d56e22208bc">
